# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will install Docker using apt.

- name:    Install prerequisites
  apt:     name={{item}} update_cache=yes
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common
- name:    Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
- name:    Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    # repo: deb [arch=$(uname -m | sed -e 's/x86_64/amd64/g')] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
- name:    Install Docker
  apt:     name=docker-ce
# - name: configure docker daemon json
#   template:
#     src: daemon.json
#     dest: "/etc/docker/daemon.json"
#   become: true
- name: replace execstart line
    lineinfile: 
      dest: /lib/systemd/system/docker.service
      regexp: '^(.*)ExecStart=/usr/bin/dockerd(.*)$' 
      line: 'ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:{{ docker.port }} -H unix:///var/run/docker.sock -s {{ docker.storagedriver }} --insecure-registry {{ groups['registry']|first }}:5000'
      backrefs: yes



# systemctl daemon-reload
# docker run -d -p 5000:5000 --restart=always --name registry registry:2
# service docker restart
# - name: add docker repo
#   apt_repository:
#     repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
#     update_cache: yes
#     state: present
#   become: true

# - name: install docker
#   apt:
#     name: "docker-engine={{ docker.version }}"
#     state: present
#     force: yes
#   become: true

# - name: configure docker
#   template:
#     src: docker.j2
#     dest: "/etc/default/docker"
#   become: true

- name: add user to docker group
  user:
    name: "{{docker.user|default(ansible_user_id)}}"
    groups: docker
    append: true
  become: true
- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
- name: restart docker service
  service:
    name: docker
    state: restarted
  become: true
