# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will install Docker using apt.

- name:    Install prerequisites
  apt:     name={{item}} update_cache=yes
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common
- name:    Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
- name:    Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
- name:    Install Docker
  apt:     name=docker-ce
# - name: add docker repo
#   apt_repository:
#     repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
#     update_cache: yes
#     state: present
#   become: true

# - name: install docker
#   apt:
#     name: "docker-engine={{ docker.version }}"
#     state: present
#     force: yes
#   become: true

- name: configure docker
  template:
    src: docker.j2
    dest: "/etc/default/docker"
  become: true

- name: add user to docker group
  user:
    name: "{{docker.user|default(ansible_user_id)}}"
    groups: docker
    append: true
  become: true

- name: restart docker service
  service:
    name: docker
    state: restarted
  become: true
