# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will install Docker using apt.

- name: install docker-ce prerequisites
  apt: name={{item}} update_cache=yes
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common

- name: add docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: add Docker APT repository
  apt_repository:
    repo: deb [arch=qqq] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: install docker-ce
  update_cache: yes
  apt:  name=docker-ce

- name: replace ExecStart line
  lineinfile: 
    dest: /lib/systemd/system/docker.service
    regexp: "^(.*)ExecStart=/usr/bin/dockerd(.*)$"
    line: "ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:{{ docker.port }} -H unix:///var/run/docker.sock -s {{ docker.storagedriver }} --insecure-registry {{ groups['registry']|first }}:5000"
    backrefs: yes

- name: add user to docker group
  user:
    name: "{{docker.user|default(ansible_user_id)}}"
    groups: docker
    append: true
  become: true

- name: reload systemd
  command: systemctl daemon-reload

- name: restart docker service
  service:
    name: docker
    state: restarted
  become: true
